spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/redeemwise_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

app:
  jwt:
    secret: YXJ1bmRld2lzZWFuZ3VsYXJrYXJkZXJlZGVlbXdpc2Vwcm9qZWN0and0c2VjcmV0a2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
    expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.redeemwise.auth: INFO
    org.springframework.security: DEBUG