spring:
  application:
    name: recommendation-service

server:
  port: 8084





eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# OpenFeign Configuration
spring.cloud.openfeign:
  client:
    config:
      card-service:
        connect-timeout: 5000
        read-timeout: 5000
      reward-service:
        connect-timeout: 5000
        read-timeout: 5000
  circuitbreaker:
    enabled: false

# SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.redeemwise.recommendation: INFO
