spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.redeemwise.discovery: INFO
    com.netflix.eureka: INFO
    org.springframework.cloud.netflix.eureka: INFO
